//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Rollno { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public bool IsBonafied { get; set; }
        public string ContactNo { get; set; }
        public int ProgrammeId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual StudentAddress StudentAddress { get; set; }
    }
}
